export const profiles = [
  {
    name: "clavicular",
    slug: "clavicular",
    image: "/profiles/clavicular.png",
    handle: "hunter-eye adjacent",
    score: 96.2,
    elite: 20,
    total: 23,
    traits: [
      "Canthal tilt: +4° positive",
      "Scleral show: minimal",
      "Iris rarity: green/hazel hybrid",
      "Eye spacing: ~1 eye-width",
      "Upper eyelid exposure: low-medium",
      "Gonial angle: ~120-123°",
      "Mandible sharpness: high",
      "Chin projection: balanced",
      "Neck-jaw contrast: clean",
      "Facial thirds: near 1:1:1",
      "Midface length: optimal",
      "Bridge: straight",
      "Tip projection: controlled",
      "Nose-mouth distance: ideal",
      "Lip fullness: natural medium",
      "Cupid's bow: present",
      "Philtrum length: short-medium",
      "Skin clarity: clear",
      "Skin reflectivity: healthy matte glow",
      "Facial fat distribution: even",
      "Hair density: high",
      "Curl pattern: loose curls",
      "Hairline: strong",
    ],
  },
  {
    name: "ASU Frat Leader",
    slug: "asu-frat-leader",
    image: "/profiles/asu-frat-leader.png",
    handle: "charisma multiplier active",
    score: 92.8,
    elite: 18,
    total: 22,
    traits: [
      "Canthal tilt: +3° positive",
      "Scleral show: low",
      "Eye expression stat: high warmth",
      "Eye spacing: balanced",
      "Gonial angle: ~122-125°",
      "Mandible visibility: medium-high",
      "Chin projection: solid",
      "Neck-jaw contrast: high",
      "Facial thirds: slight lower-third dominance",
      "Midface ratio: balanced",
      "Bridge: straight-athletic",
      "Tip: compact",
      "Nose harmony stat: high",
      "Lip fullness: natural medium",
      "Smile width: high",
      "Philtrum length: balanced",
      "Skin clarity: clear",
      "Facial leanness: athletic",
      "Color tone: even",
      "Hair density: high",
      "Volume: controlled chaos",
      "Hairline stability: strong",
    ],
  },
  {
    name: "Androgen",
    slug: "androgen",
    image: "/profiles/androgen.png",
    handle: "hunter-eye buff",
    score: 98.4,
    elite: 21,
    total: 24,
    traits: [
      "Canthal tilt: +5° positive",
      "Scleral show: minimal",
      "Eye depth: deep-set",
      "Eye symmetry: high",
      "Gonial angle: ~120°",
      "Jawline sharpness: high",
      "Chin projection: strong",
      "Cheekbone prominence: high",
      "Facial thirds: very balanced",
      "Midface length: compact",
      "Bridge: straight",
      "Tip definition: refined",
      "Nose harmony: high",
      "Lip fullness: medium-full",
      "Cupid's bow: defined",
      "Philtrum: balanced",
      "Skin clarity: clear",
      "Facial leanness: high",
      "Tone uniformity: even",
      "Hair density: high",
      "Texture: thick + wavy",
      "Hairline: strong",
    ],
  },
  {
    name: "marlon",
    slug: "marlon",
    image: "/profiles/marlon.png",
    handle: "friendly hunter-eye hybrid",
    score: 89.7,
    elite: 16,
    total: 20,
    traits: [
      "Canthal tilt: +3-4° positive",
      "Scleral show: low",
      "Eye contact aura: strong",
      "Gonial angle: ~123°",
      "Jawline visibility: high",
      "Chin projection: balanced",
      "Cheekbone structure: subtle but defined",
      "Facial thirds: slight lower-third dominance",
      "Midface ratio: balanced",
      "Bridge: straight",
      "Tip: compact",
      "Nose harmony: high",
      "Lip fullness: medium",
      "Smile readiness stat: high",
      "Philtrum length: balanced",
      "Skin clarity: clear",
      "Tone uniformity: even",
      "Facial fat distribution: lean",
      "Hair density: high",
      "Hairline stability: strong",
    ],
  },
  {
    name: "Orangie",
    slug: "orangie",
    image: "/profiles/orangie.png",
    handle: "angles help",
    score: 75.5,
    elite: 10,
    total: 16,
    traits: [
      "Canthal tilt: positive, not extreme",
      "Under-eye area: slightly tired",
      "Jawline: defined but not razor sharp",
      "Cheekbones: present, not model-tier projection",
      "Overall proportions: balanced",
      "No highly rare standout trait",
      "Hair is carrying major visual weight",
      "Without volume, score drops a tier",
    ],
  },
  {
    name: "Ethanprosper",
    slug: "ethanprosper",
    image: "/profiles/ethan.png",
    handle: "semi masculine",
    score: 70.1,
    elite: 9,
    total: 15,
    traits: [
      "Eyes: good shape with neutral tilt",
      "Jaw: strong",
      "Chin projection: solid",
      "Not hyper-angular, but semi masculine",
      "Proportions: slightly below-average harmony",
      "Not perfect-ratio, mid genetics",
      "Longer textured cut would boost",
    ],
  },
  {
    name: "Clav Body Guard Joe",
    slug: "clav-body-guard-joe",
    image: "/profiles/clav-body-guard-joe.png",
    handle: "candid frame check",
    score: 66.4,
    elite: 8,
    total: 15,
    traits: [
      "Canthal tilt: neutral to slightly positive",
      "Scleral show: normal",
      "Eye area support: looks average",
      "Eye harmony: balanced with face",
      "Gonial angle: ~125-130° estimate",
      "Jawline visibility: medium",
      "Chin projection: appears proportional",
      "Cheekbone projection: hard to judge",
      "Facial thirds: generally balanced",
      "Midface ratio: average",
      "Symmetry read: normal",
      "Bridge: looks straight",
      "Tip projection: moderate (proportional)",
      "Nose harmony: fits face well",
      "Lip fullness: medium (balanced)",
      "Neutral expression: slightly tense/candid",
      "Philtrum ratio: normal",
      "Hairline: looks solid",
      "Cut/style: simple",
      "Hair density: appears normal",
    ],
  },
  {
    name: "Asu freshman",
    slug: "asu-freshman",
    image: "/profiles/asu-freshman.png",
    handle: "freshman smile buff",
    score: 73.8,
    elite: 10,
    total: 18,
    traits: [
      "Canthal tilt: slightly positive (~+2°)",
      "Scleral show: normal",
      "Eye spacing: balanced",
      "Expression: smile boosts perception",
      "Gonial angle (jaw): ~125-128°",
      "Jaw visibility: moderate",
      "Chin projection: solid",
      "Cheekbone projection: moderate",
      "Facial thirds: slight lower-third dominance",
      "Midface ratio: average",
      "Symmetry read: good but not elite",
      "Bridge: straight",
      "Tip: rounded",
      "Nose harmony: fits face well",
      "Lip fullness: medium",
      "Philtrum: normal",
      "Skin clarity: looks clear",
      "Facial leanness: moderate",
      "Hair density: good",
      "Style: casual, not optimized",
      "Hairline: solid",
    ],
  },
  {
    name: "Neutral Baseline",
    slug: "neutral-baseline",
    image: "/profiles/neutral-baseline.png",
    handle: "generic harmony",
    score: 63.9,
    elite: 7,
    total: 14,
    traits: [
      "Canthal tilt: neutral",
      "Eye area: slightly softer",
      "Jawline: moderate",
      "Cheekbones: average",
      "Facial harmony: balanced but generic",
      "Nothing highly distinctive",
      "Hair density: good",
      "Current style: safe, not enhancing much",
    ],
  },
];

export const multipliers = {
  daily: 1,
  weekly: 0.97,
  monthly: 1.03,
};

export function initials(name) {
  const words = name.split(/\s+/).filter(Boolean);
  if (words.length === 1) return words[0].slice(0, 2).toUpperCase();
  return `${words[0][0]}${words[1][0]}`.toUpperCase();
}

export function tier(score) {
  if (score >= 96) return "TERA CHAD";
  if (score >= 92) return "GIGA CHAD";
  if (score >= 86) return "CHAD";
  if (score >= 80) return "NORMIE CHAD";
  if (score >= 72) return "NORMIE";
  if (score >= 64) return "CHUD";
  return "GOBLINCHAD";
}

export function formatScore(score) {
  return `+${score.toFixed(2)} MOG (${tier(score)})`;
}
