export const profiles = [
  {
    name: "Androgen",
    slug: "androgen",
    image: "/profiles/androgen.png",
    handle: "hunter-eye buff",
    rankLabel: "Gigachad",
    score: 8.5,
    elite: 21,
    total: 24,
    traits: [
      "Canthal tilt: +5° positive",
      "Scleral show: Minimal",
      "Eye depth: Deep-set",
      "Eye symmetry: High",
      "Gonial angle (jaw): ~120°",
      "Jawline sharpness: High",
      "Chin projection: Strong",
      "Cheekbone prominence: High",
      "Facial thirds: Very balanced",
      "Midface length: Compact",
      "Bridge: Straight",
      "Tip definition: Refined",
      "Nose harmony: High",
      "Lip fullness: Medium-full",
      "Cupid's bow: Defined",
      "Philtrum: Balanced",
      "Skin clarity: Clear",
      "Facial leanness: High",
      "Tone uniformity: Even",
      "Hair density: High",
      "Texture: Thick + wavy",
      "Hairline: Strong",
    ],
  },
  {
    name: "clavicular",
    slug: "clavicular",
    image: "/profiles/clavicular.png",
    handle: "hunter-eye adjacent",
    rankLabel: "Chad",
    score: 8.0,
    elite: 20,
    total: 23,
    traits: [
      "Canthal tilt: +4° positive",
      "Scleral show: Minimal",
      "Iris color rarity: Green / hazel hybrid",
      "Eye spacing: ~1 eye-width apart",
      "Upper eyelid exposure: Low-medium",
      "Gonial angle (jaw): ~120-123°",
      "Mandible sharpness: High",
      "Chin projection: Balanced",
      "Neck-jaw contrast: Clean",
      "Facial thirds: Near 1:1:1",
      "Midface length: Optimal",
      "Bridge: Straight",
      "Tip projection: Controlled",
      "Nose-to-mouth distance: Ideal",
      "Lip fullness: Natural medium",
      "Cupid's bow definition: Present",
      "Philtrum length: Short-medium",
      "Skin clarity: Clear",
      "Skin reflectivity: Healthy matte glow",
      "Facial fat distribution: Even",
      "Hair density: High",
      "Curl pattern: Loose curls",
      "Hairline: Strong",
    ],
  },
  {
    name: "David Laid",
    slug: "david-laid",
    image: "/profiles/david-laid.png",
    handle: "hunter-eye hybrid",
    rankLabel: "Chad",
    score: 7.5,
    elite: 20,
    total: 24,
    traits: [
      "Canthal tilt: Slight positive (~+2-3°)",
      "Scleral show: Low",
      "Eye depth: Moderately deep-set",
      "Expression: Neutral-serious",
      "Gonial angle (jaw): ~120-123°",
      "Jawline sharpness: High",
      "Chin projection: Solid",
      "Cheekbone projection: Moderate-high",
      "Facial thirds: Slight lower-third dominance",
      "Midface ratio: Average",
      "Symmetry read: Above average",
      "Bridge: Straight",
      "Tip: Defined but not sharp",
      "Nose harmony: Good",
      "Lip fullness: Medium",
      "Neutral expression rating: Strong",
      "Philtrum: Normal",
      "Skin clarity: Clear",
      "Facial leanness: High",
      "Soft tissue: Tight",
      "Hair density: Good",
      "Style: Casual textured",
      "Hairline: Stable",
    ],
  },
  {
    name: "Murad",
    slug: "slickback-subject",
    image: "/profiles/slickback-subject.png",
    handle: "soft hunter-eye",
    rankLabel: "Chad",
    score: 7.0,
    elite: 19,
    total: 23,
    traits: [
      "Canthal tilt: Slight positive (~+3-4°)",
      "Scleral show: Low",
      "Eye depth: Deep-set",
      "Gonial angle (jaw): ~120-122°",
      "Jawline visibility: High",
      "Chin projection: Strong",
      "Cheekbone projection: Noticeable",
      "Facial thirds: Balanced",
      "Midface ratio: Slightly compact",
      "Symmetry read: Above average",
      "Bridge: Straight",
      "Tip: Defined",
      "Nose harmony: High",
      "Lip fullness: Medium",
      "Neutral-expression rating: Strong",
      "Philtrum: Balanced",
      "Skin clarity: Looks smooth",
      "Facial leanness: Lean",
      "Texture perception: Enhanced by grayscale",
      "Hair density: Good",
      "Style: Slicked back",
      "Hairline: Strong",
    ],
  },
  {
    name: "ASU Frat Leader",
    slug: "asu-frat-leader",
    image: "/profiles/asu-frat-leader.png",
    handle: "charisma multiplier active",
    rankLabel: "Chadlite",
    score: 7.0,
    elite: 18,
    total: 22,
    traits: [
      "Canthal tilt: +3° positive",
      "Scleral show: Low",
      "Eye expression stat: High warmth",
      "Eye spacing: Balanced",
      "Gonial angle (jaw): ~122-125°",
      "Mandible visibility: Medium-high",
      "Chin projection: Solid",
      "Neck-jaw contrast: High",
      "Facial thirds: Slight lower-third dominance",
      "Midface ratio: Balanced",
      "Bridge: Straight-athletic",
      "Tip: Compact",
      "Nose harmony stat: High",
      "Lip fullness: Natural medium",
      "Smile width: High",
      "Philtrum length: Balanced",
      "Skin clarity: Clear",
      "Facial leanness: Athletic",
      "Color tone: Even",
      "Hair density: High",
      "Volume: Controlled chaos",
      "Hairline stability: Strong",
    ],
  },
  {
    name: "CookieKing",
    slug: "cookieking",
    image: "/profiles/cookieking.png",
    handle: "curl-pattern chad",
    rankLabel: "Chad",
    score: 7.0,
    elite: 17,
    total: 22,
    traits: [
      "Canthal tilt: Slight positive (~+3°)",
      "Scleral show: Low",
      "Eye spacing: Balanced",
      "Gonial angle (jaw): ~122-125°",
      "Jawline visibility: Good",
      "Chin projection: Solid",
      "Cheekbone projection: Moderate-high",
      "Facial thirds: Close to balanced",
      "Midface ratio: Slightly compact",
      "Symmetry read: Above average",
      "Bridge: Straight",
      "Tip: Refined",
      "Nose harmony: High",
      "Lip fullness: Medium-full",
      "Cupid's bow: Defined",
      "Philtrum: Balanced",
      "Facial leanness: Lean",
      "Hair density: High",
      "Curl pattern: Loose curls",
      "Hairline: Strong",
    ],
  },
  {
    name: "marlon",
    slug: "marlon",
    image: "/profiles/marlon.png",
    handle: "hunter-eye hybrid",
    rankLabel: "Terachad",
    score: 9.0,
    elite: 16,
    total: 20,
    traits: [
      "Canthal tilt: +3-4° positive",
      "Scleral show harmony stat: High",
      "Eye contact aura: Strong",
      "Gonial angle (jaw): ~123°",
      "Jawline visibility: High",
      "Chin projection: Balanced",
      "Cheekbone structure: Subtle but defined",
      "Facial thirds: Slight lower-third dominance",
      "Midface ratio: Balanced",
      "Bridge: Straight",
      "Tip: Compact",
      "Nose harmony: High",
      "Lip fullness: Medium",
      "Smile readiness stat: High",
      "Philtrum length: Balanced",
      "Skin clarity: Clear",
      "Tone uniformity: Even",
      "Facial fat distribution: Lean",
      "Hair density: High",
      "Hairline stability: Strong",
    ],
  },
  {
    name: "Blame Tony",
    slug: "blame-tony",
    image: "/profiles/blame-tony.png",
    handle: "neutral-positive frame",
    rankLabel: "Chad",
    score: 7.5,
    elite: 17,
    total: 22,
    traits: [
      "Canthal tilt: Neutral to slight positive (~+2°)",
      "Scleral show: Low",
      "Eye depth: Moderate",
      "Gonial angle: ~120-123°",
      "Jawline visibility: High",
      "Chin projection: Solid",
      "Cheekbone projection: Moderate",
      "Facial thirds: Slight lower-third dominance",
      "Midface ratio: Average",
      "Symmetry read: Above average",
      "Bridge: Straight",
      "Tip: Rounded-defined",
      "Nose harmony: Good",
      "Lip fullness: Medium",
      "Neutral-expression rating: Strong",
      "Philtrum: Normal",
      "Skin clarity: Looks clear",
      "Facial leanness: Lean",
      "Texture: Smooth in this lighting",
      "Hair density: High",
      "Style: Short textured top",
      "Hairline: Strong",
    ],
  },
  {
    name: "Anukein's Brother",
    slug: "anukeins-brother",
    image: "/profiles/anukeins-brother.png",
    handle: "brooding compact frame",
    rankLabel: "Gigachad",
    score: 8.5,
    elite: 16,
    total: 22,
    traits: [
      "Canthal tilt: Slight positive (~+3°)",
      "Scleral show: Low",
      "Eye depth: Moderately deep-set",
      "Expression: Serious/brooding",
      "Gonial angle (jaw): ~122-125°",
      "Jawline visibility: Moderate",
      "Chin projection: Solid",
      "Cheekbone projection: Moderate",
      "Facial thirds: Close to balanced",
      "Midface ratio: Slightly compact",
      "Symmetry read: Above average",
      "Bridge: Straight",
      "Tip: Defined",
      "Nose harmony: High",
      "Lip fullness: Medium",
      "Neutral-expression rating: Strong",
      "Philtrum: Normal",
      "Skin clarity: Looks clear",
      "Facial leanness: Moderate",
      "Soft tissue: Youthful fullness",
      "Hair density: High",
      "Hairline: Strong",
    ],
  },
  {
    name: "Micheal Sears",
    slug: "micheal-sears",
    image: "/profiles/micheal-sears.png",
    handle: "wide mandible build",
    rankLabel: "Chad",
    score: 7.0,
    elite: 14,
    total: 21,
    traits: [
      "Canthal tilt: Neutral to slightly negative",
      "Eyelid exposure: Mildly hooded",
      "Eye spacing: Good",
      "Jaw: Very strong mandible (wide and square)",
      "Chin: Forward and broad",
      "Cheekbones: Moderate projection",
      "Facial thirds: Lower-third slightly dominant",
      "Facial width-to-height ratio: Wider side",
      "Symmetry: Good but not elite",
      "Nasal base: Wide",
      "Nasal tip: Slightly bulky",
      "Nose read: Masculine but less aesthetic",
      "Lips: Thinner",
      "Resting expression: Stern",
      "Facial leanness: Lean",
      "Skin quality: Good",
      "Dimorphism: Very high (masculine-dominant face)",
    ],
  },
  {
    name: "Tristan Tate",
    slug: "tristan-tate",
    image: "/profiles/tristan-tate.png",
    handle: "groomed masculine frame",
    rankLabel: "chadlite",
    score: 6.5,
    elite: 14,
    total: 20,
    traits: [
      "Canthal tilt: Neutral",
      "Eye spacing: Good",
      "Alert expression helps",
      "Jawline: Defined",
      "Chin: Strong",
      "Cheekbones: Visible but not dramatic",
      "Facial thirds: Balanced",
      "Symmetry: Above average",
      "Nose: Straight and proportional",
      "Nose size: Slightly large but fits masculine look",
      "Lips: Medium",
      "Light stubble frames face well",
      "Face: Relatively lean",
      "Hair: Styled and maintained",
      "Grooming level: High",
    ],
  },
  {
    name: "Andrew Tate",
    slug: "andrew-tate",
    image: "/profiles/andrew-tate.png",
    handle: "masculine beard frame",
    rankLabel: "chadlite",
    score: 6.0,
    elite: 12,
    total: 19,
    traits: [
      "Eyes: Neutral tilt",
      "Eye depth: Slightly deep-set",
      "Expression: Strong focused",
      "Jawline: Good but not razor-sharp",
      "Chin: Solid masculine",
      "Cheekbones: Moderate",
      "Facial harmony: Balanced overall",
      "Symmetry: Decent, not elite",
      "Nose: Slightly large but fits face",
      "Aesthetic direction: Masculine rather than aesthetic",
      "Lips: Thinner side",
      "Beard framing: Strong lower-face boost",
      "Skin quality: Normal",
      "Facial leanness: Not super lean",
      "Shaved head works well",
    ],
  },
  {
    name: "Orangie",
    slug: "orangie",
    image: "/profiles/orangie.png",
    handle: "angles help",
    rankLabel: "Normie",
    score: 5.0,
    elite: 10,
    total: 16,
    traits: [
      "Canthal tilt: Positive, but not extreme",
      "Under-eye area: Slightly tired looking",
      "Jawline: Defined but not razor sharp",
      "Cheekbones: Present but not model-tier projection",
      "Balanced overall proportions",
      "Nothing strikingly elite or rare",
      "Hair doing a lot of the work",
      "Without volume, face drops a tier",
    ],
  },
  {
    name: "Asu freshman",
    slug: "asu-freshman",
    image: "/profiles/asu-freshman.png",
    handle: "freshman smile buff",
    rankLabel: "Chad",
    score: 7.0,
    elite: 10,
    total: 18,
    traits: [
      "Canthal tilt: Slightly positive (~+2°)",
      "Scleral show: Normal",
      "Eye spacing: Balanced",
      "Expression: Smile boosting perception",
      "Gonial angle (jaw): ~125-128°",
      "Jaw visibility: Moderate",
      "Chin projection: Solid",
      "Cheekbone projection: Moderate",
      "Facial thirds: Slight lower-third dominance",
      "Midface ratio: Average",
      "Symmetry read: Good but not elite",
      "Bridge: Straight",
      "Tip: Rounded",
      "Nose harmony: Fits face well",
      "Lip fullness: Medium",
      "Philtrum: Normal",
      "Skin clarity: Looks clear",
      "Facial leanness: Moderate",
      "Hair density: Good",
      "Style: Casual, not optimized",
      "Hairline: Solid",
    ],
  },
  {
    name: "The DUve",
    slug: "the-duve",
    image: "/profiles/the-duve.png",
    handle: "balanced baseline",
    rankLabel: "Normie",
    score: 5.0,
    elite: 9,
    total: 17,
    traits: [
      "Canthal tilt: Neutral",
      "Eye area: Slightly hooded",
      "Eye spacing: Balanced",
      "Jawline: Decent but not sharp",
      "Chin projection: Normal",
      "Cheekbones: Mild",
      "Facial thirds: Pretty balanced",
      "Midface: Average length",
      "Symmetry: Normal",
      "Skin looks clear",
      "Slight facial softness",
      "Hair density: Good",
      "Simple style not optimized for aesthetics",
    ],
  },
  {
    name: "Ethanprosper",
    slug: "ethanprosper",
    image: "/profiles/ethan.png",
    handle: "semi masculine",
    rankLabel: "Normie",
    score: 5.0,
    elite: 9,
    total: 15,
    traits: [
      "Eyes: Good shape, neutral tilt",
      "Strong jaw",
      "Solid chin projection",
      "Not hyper-angular, but semi masculine",
      "Proportions: Slightly below-average harmony",
      "Not perfect ratio, mid genetics",
      "Longer textured cut would boost",
    ],
  },
  {
    name: "Clav Body Guard Joe",
    slug: "clav-body-guard-joe",
    image: "/profiles/clav-body-guard-joe.png",
    handle: "candid frame check",
    rankLabel: "chadlite",
    score: 6.0,
    elite: 8,
    total: 15,
    traits: [
      "Canthal tilt: Neutral to slightly positive",
      "Scleral show: Normal",
      "Eye area support: Looks average",
      "Eye harmony: Balanced with face",
      "Gonial angle: ~125-130° estimate",
      "Jawline visibility: Medium",
      "Chin projection: Appears proportional",
      "Cheekbone projection: Hard to judge",
      "Facial thirds: Look generally balanced",
      "Midface ratio: Average",
      "Symmetry read: Normal",
      "Bridge: Looks straight",
      "Tip projection: Moderate (proportional)",
      "Nose harmony: Fits face well",
      "Lip fullness: Medium (balanced)",
      "Neutral expression: Slightly tense/candid",
      "Philtrum ratio: Normal",
      "Hairline: Looks solid",
      "Cut/style: Simple",
      "Density: Appears normal",
    ],
  },
  {
    name: "Cented",
    slug: "cented",
    image: "/profiles/cented.png",
    handle: "generic harmony",
    rankLabel: "High tier Normie",
    score: 5.5,
    elite: 7,
    total: 14,
    traits: [
      "Canthal tilt: Neutral",
      "Slightly softer eye area",
      "Jawline: Moderate",
      "Cheekbones: Average",
      "Balanced facial harmony but generic",
      "Nothing super distinctive",
      "Good hair density",
      "Style is safe, not enhancing much",
    ],
  },
  {
    name: "Frankdegods",
    slug: "frankdegods",
    image: "/profiles/frankdegods.png",
    handle: "glasses-obscured eye area",
    rankLabel: "Sub 5 Goblin Chad",
    score: 4.5,
    elite: 6,
    total: 16,
    traits: [
      "Canthal tilt: Neutral to slightly negative",
      "Eyelid exposure: Mildly hooded/droopy",
      "Eye spacing: Slightly close-set",
      "Eye support: Average, slight tired look",
      "Jawline: Soft, low definition",
      "Chin projection: Average",
      "Cheekbone projection: Low to moderate",
      "Facial thirds: Slightly long midface",
      "Facial width-to-height: Slightly narrow",
      "Symmetry: Normal, not elite",
      "Nasal bridge: Straight",
      "Nasal tip: Slight downward tilt",
      "Nasal size: Prominent for face",
      "Upper lip fullness: Thin",
      "Lower lip fullness: Moderate",
      "Resting expression: Tired/neutral",
      "Skin quality: Normal/clear",
      "Facial fat: Slight softness",
      "Hair density: Good",
      "Hair styling: Unkempt",
      "Dimorphism: Moderate to low",
    ],
  },
  {
    name: "Finnbags",
    slug: "finnbags",
    image: "/profiles/finnbags.png",
    handle: "wide-eye neutral read",
    rankLabel: "Sub 5 Goblin Chad",
    score: 4.0,
    elite: 5,
    total: 15,
    traits: [
      "Canthal tilt: Neutral",
      "Eyelid exposure: High (wide-open look)",
      "Eye spacing: Average to slightly wide",
      "Eye support: Weak under-eye support",
      "Jawline: Soft, low definition",
      "Chin projection: Slightly weak",
      "Cheekbone projection: Low",
      "Facial thirds: Midface slightly long",
      "Facial width-to-height: Narrow/oval",
      "Symmetry: Average",
      "Nasal bridge: Straight",
      "Nasal tip: Rounded",
      "Nasal size: Slightly large for face",
      "Upper lip fullness: Thin",
      "Lower lip fullness: Moderate",
      "Resting expression: Blank/neutral",
      "Skin quality: Fine",
      "Facial fat: Moderate softness",
      "Hair density: Good",
      "Hair styling: Basic, not optimized",
      "Hair volume: Helps slightly",
      "Dimorphism: Moderate",
    ],
  },
];

export const multipliers = {
  daily: 1,
  weekly: 0.97,
  monthly: 1.03,
};

export function initials(name) {
  const words = name.split(/\s+/).filter(Boolean);
  if (words.length === 1) return words[0].slice(0, 2).toUpperCase();
  return `${words[0][0]}${words[1][0]}`.toUpperCase();
}

export function tier(score) {
  if (score >= 8.75) return "Terachad";
  if (score >= 8.25) return "Gigachad";
  if (score >= 7.0) return "Chad";
  if (score >= 6.0) return "chadlite";
  if (score >= 5.25) return "High tier Normie";
  if (score >= 5.0) return "Normie";
  return "Sub 5 Goblin Chad";
}

function tierEmoji(rankLabel) {
  const key = String(rankLabel || "").toLowerCase();

  if (key.includes("tera chad") || key.includes("terachad")) return "🥇";
  if (key.includes("giga chad") || key.includes("gigachad")) return "🥈";
  if (key.includes("goblin")) return "👹";
  if (key.includes("chud")) return "📉";
  if (key.includes("chadlite")) return "🔹";
  if (key.includes("normie")) return "⚖️";
  if (key.includes("chad")) return "🥉";

  return "";
}

function stableHash(input) {
  let hash = 2166136261;
  for (let i = 0; i < input.length; i += 1) {
    hash ^= input.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return hash >>> 0;
}

function randomizedMogScore(score, seedKey) {
  const clamped = Math.min(Math.max(score, 0), 10);
  const seed = stableHash(String(seedKey || "mogscan"));
  const variance = (seed % 100) / 100; // 0.00 to 0.99
  const randomized = clamped * 10 + variance;
  return Math.min(Math.max(randomized, 40), 99.9);
}

export function formatScore(_score, rankLabel, _seedKey = "") {
  const label = rankLabel || tier(_score);
  const emoji = tierEmoji(label);
  return `${emoji ? `${emoji} ` : ""}${label}`;
}
